/* tslint:disable */
/* eslint-disable */
/**
 * Netforenotes app API docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteListItemAllOf
 */
export interface NoteListItemAllOf {
    /**
     * 
     * @type {string}
     * @memberof NoteListItemAllOf
     */
    id: string;
}

/**
 * Check if a given object implements the NoteListItemAllOf interface.
 */
export function instanceOfNoteListItemAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function NoteListItemAllOfFromJSON(json: any): NoteListItemAllOf {
    return NoteListItemAllOfFromJSONTyped(json, false);
}

export function NoteListItemAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteListItemAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NoteListItemAllOfToJSON(value?: NoteListItemAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

