/* tslint:disable */
/* eslint-disable */
/**
 * Netforenotes app API docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteListItem
 */
export interface NoteListItem {
    /**
     * 
     * @type {string}
     * @memberof NoteListItem
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof NoteListItem
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof NoteListItem
     */
    id: string;
}

/**
 * Check if a given object implements the NoteListItem interface.
 */
export function instanceOfNoteListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function NoteListItemFromJSON(json: any): NoteListItem {
    return NoteListItemFromJSONTyped(json, false);
}

export function NoteListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'createdAt': json['created_at'],
        'id': json['id'],
    };
}

export function NoteListItemToJSON(value?: NoteListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'created_at': value.createdAt,
        'id': value.id,
    };
}

