/* tslint:disable */
/* eslint-disable */
/**
 * Netforenotes app API docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteCreationAllOf
 */
export interface NoteCreationAllOf {
    /**
     * 
     * @type {string}
     * @memberof NoteCreationAllOf
     */
    body: string;
}

/**
 * Check if a given object implements the NoteCreationAllOf interface.
 */
export function instanceOfNoteCreationAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function NoteCreationAllOfFromJSON(json: any): NoteCreationAllOf {
    return NoteCreationAllOfFromJSONTyped(json, false);
}

export function NoteCreationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function NoteCreationAllOfToJSON(value?: NoteCreationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}

