/* tslint:disable */
/* eslint-disable */
/**
 * Netforenotes app API docs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteCreation
 */
export interface NoteCreation {
    /**
     * 
     * @type {string}
     * @memberof NoteCreation
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof NoteCreation
     */
    createdAt: number;
    /**
     * 
     * @type {string}
     * @memberof NoteCreation
     */
    body: string;
}

/**
 * Check if a given object implements the NoteCreation interface.
 */
export function instanceOfNoteCreation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function NoteCreationFromJSON(json: any): NoteCreation {
    return NoteCreationFromJSONTyped(json, false);
}

export function NoteCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'createdAt': json['created_at'],
        'body': json['body'],
    };
}

export function NoteCreationToJSON(value?: NoteCreation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'created_at': value.createdAt,
        'body': value.body,
    };
}

